{% set name = "jplephem" %}
{% set version = "2.10" %}
{% set sha256 = "d8a6a249b33f7a1d34d3a9ca90be9566609212ecd2e8a45d3becd29888d28133" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001_use-setuptools.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  requires:
    - curl
  imports:
    - jplephem
  commands:
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de421.bsp
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp
    - curl -sS -O https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/de405.bsp
    - curl -sS -O ftp://ssd.jpl.nasa.gov/pub/eph/planets/test-data/430/testpo.430
    - python -m unittest discover jplephem.test
    - python -m jplephem.jpltest

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT
  license_file: LICENSE.txt
  license_file: LICENSE.txt
  summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

extra:
  recipe-maintainers:
    - juanlu001
    - brandon-rhodes
    - jochym
